### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by BastiHz** [BastiHz/pygame_template#1]
Remember: Keep this template minimal.

- [ ] Make an `images` directory with a sample image. Use it to demonstrate loading of assets and how they may be accessed from within the state instances using the class attribute `State.images`.
- [ ] Rename sample "Test" state.
- [ ] Demonstrate switching between states.
